
# Development overrides for docker-compose.yml
services:
  icecast:
    environment:
      - ICECAST_ADMIN_PASSWORD=hackme
      - ICECAST_PASSWORD=hackme
      - ICECAST_HOSTNAME=localhost
    volumes:
      - ./infra/icecast.xml:/etc/icecast2/icecast.xml:ro

  liquidsoap:
    ports:
      - "1234:1234"  # Telnet interface for debugging
      - "8080:8080"  # HTTP metadata endpoint
    environment:
      - LIQUIDSOAP_LOG_LEVEL=3

  api:
    ports:
      - "8001:8000"  # Expose API for direct access
    environment:
      - RELOAD=true
    volumes:
      - ./services/api:/app:rw  # Live reload during development
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  dj-worker:
    environment:
      - RELOAD=true
    volumes:
      - ./services/dj-worker:/app:rw  # Live reload during development

  proxy:
    ports:
      - "3000:80"   # Development port mapping
    volumes:
      - ./infra/Caddyfile.dev:/etc/caddy/Caddyfile:ro
    depends_on:
      - api
      - web-dev
      - icecast
    
  web-dev:
    image: node:18
    working_dir: /app
    ports:
      - "3001:3000"  # Direct access to React dev server
    environment:
      - CHOKIDAR_USEPOLLING=true  # For hot reload in containers
    volumes:
      - ./web:/app:rw
      - /app/node_modules  # Preserve node_modules in container
    # Always ensure deps are installed, then run Vite dev server
    command: ["sh","-lc","npm ci; npm run dev -- --host 0.0.0.0 --port 3000"]

  # Development utilities
  db-admin:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  # Development volume for easier debugging
  logs:
    driver: local
